// Code generated by mfd-generator v0.5.1&#43;dirty; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (u User) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(u.Login) > 64 {
		errors[Columns.User.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.Password) > 64 {
		errors[Columns.User.Password] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.AuthKey) > 32 {
		errors[Columns.User.AuthKey] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (e Expense) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(e.Currency) > 12 {
		errors[Columns.Expense.Currency] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
