version: "3.9"

services:
  bot:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: saldo-bot
    expose:
      - "8075"
    volumes:
      - ../models/:/app/models/
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      timeout: 2s
      retries: 2
      start_period: 5s
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../docs:/docs
      - pgdata:/var/lib/postgresql/

  prometheus:
    image: prom/prometheus:latest
    container_name: saldo-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - bot
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: saldo-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
